# base content
---

footerData:
  - title: 'Get Started'
    info:
      - name: 'Why Auto-DL'
        link: "#"

      - name: 'Install'
        link: "https://docs.auto-dl.tech/en/latest/installing.html"

      - name: 'Pricing'
        link: "/pricing"

  - title: 'Support'
    info:
      - name: 'Docs'
        link: "docs.auto-dl.tech"

      - name: 'FAQ'
        link: "https://docs.auto-dl.tech/en/latest/userguide.html"

      - name: 'Feedback'
        link: "mailto:info@auto-dl.tech"

  - title: 'Organization'
    info:
      - name: 'About'
        link: "#"

      - name: 'Jobs'
        link: "#"

      - name: 'Contact'
        link: "mailto:info@auto-dl.tech"

  - title: 'Development'
    info:
      - name: 'Contribute'
        link: "https://github.com/Auto-DL/Auto-DL/blob/main/CONTRIBUTING.md"

      - name: 'Roadmap'
        link: "#todo"

      - name: 'Work with Us'
        link: "https://autodl.slack.com/join/shared_invite/zt-qagxiwub-ywRM_oBvvF~F7YNtlBqy_Q#/shared-invite/email"
